	asm_line.set( "LABEL", "", "_sub_input_all_free" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "de", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "hl", "svars_input_free_str0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "a", "7" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_input_all_free_loop" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "c", "[hl]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "inc", "", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "b", "[hl]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "or", "", "a", "a" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ex", "", "de", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "sbc", "", "hl", "bc" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ex", "", "de", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "jr", "nc", "_sub_input_all_free_no_swap" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "e", "c" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "d", "b" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "[hl]", "b" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "dec", "", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "[hl]", "c" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "inc", "", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_input_all_free_no_swap" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "inc", "", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "dec", "", "a" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "jr", "nz", "_sub_input_all_free_loop" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ld", "", "a", "e" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "or", "", "a", "d" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ret", "Z" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ex", "", "de", "hl" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "call", "", "free_string" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "jr", "", "_sub_input_all_free" );
	this->subroutines.push_back( asm_line );
