	this->add_label( "bios_frcsng", "0x02FB2" );
	this->add_label( "bios_decmul", "0x027e6" );
	this->add_label( "bios_frcint", "0x02f8a" );
	this->add_label( "blib_get_sin_table", "0x040de" );
	this->add_label( "bios_line", "0x058FC" );
	this->add_label( "work_rg9sav", "0x0FFE8" );
	this->add_label( "work_aspct1", "0x0f40b" );
	this->add_label( "work_aspct2", "0x0f40d" );
	this->add_label( "work_buf", "0x0f55e" );
	this->add_label( "work_valtyp", "0x0f663" );
	this->add_label( "work_dac", "0x0f7f6" );
	this->add_label( "work_scrmod", "0x0fcaf" );
	this->add_label( "work_circle_x_shift", "work_buf + 65" );
	this->add_label( "work_circle_quadrant0", "work_buf + 66" );
	this->add_label( "work_circle_quadrant1", "work_buf + 67" );
	this->add_label( "work_circle_quadrant2", "work_buf + 68" );
	this->add_label( "work_circle_quadrant3", "work_buf + 69" );
	this->add_label( "work_circle_centerx", "work_buf + 70" );
	this->add_label( "work_circle_centery", "work_buf + 72" );
	this->add_label( "work_circle_radiusx", "work_buf + 74" );
	this->add_label( "work_circle_radiusy", "work_buf + 76" );
	this->add_label( "work_circle_prev_cxoff1", "work_buf + 78" );
	this->add_label( "work_circle_prev_cyoff1", "work_buf + 80" );
	this->add_label( "work_circle_prev_cxoff2", "work_buf + 82" );
	this->add_label( "work_circle_prev_cyoff2", "work_buf + 84" );
	this->add_label( "work_circle_cxoff1", "work_buf + 86" );
	this->add_label( "work_circle_cyoff1", "work_buf + 88" );
	this->add_label( "work_circle_cxoff2", "work_buf + 90" );
	this->add_label( "work_circle_cyoff2", "work_buf + 92" );
	this->add_label( "work_arg", "0x0F847" );
	this->add_label( "bios_chgmod", "0x0005F" );
	this->add_label( "work_gxpos", "0x0FCB3" );
	this->add_label( "work_gypos", "0x0FCB5" );
	this->add_label( "work_aspect", "0x0F931" );
	this->add_label( "work_cpcnt", "0x0F939" );
	this->add_label( "work_crcsum", "0x0F93D" );
	this->add_label( "work_csclxy", "0x0F941" );
	this->add_label( "work_savea", "0x0F942" );
	this->add_label( "work_savem", "0x0F944" );
	this->add_label( "work_cxoff", "0x0F945" );
	this->add_label( "work_cyoff", "0x0F947" );
	this->add_label( "bios_setatr", "0x0011A" );

	CSINGLE_REAL value;
	value.set( "40.7437" );
	std::string s_407437 = p_info->constants.add( value );

	this->activate_ld_arg_single_real();
	this->activate_ld_dac_single_real();
	this->activate_ld_de_hl_for_single();

	asm_line.set( "COMMENT", "", " Circle routine --------------------------------------------------------------" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "sub_circle" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Calclate vertical radius" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "work_aspect" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "ld_arg_single_real" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_radiusx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_dac + 2]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_valtyp]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_frcsng" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_decmul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_frcint" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_dac + 2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_aspct2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SRL", "", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RR", "", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_radiusy]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Convert Start angle to 0...255." );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "work_cpcnt" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "ld_arg_single_real" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "single_407437" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "ld_dac_single_real" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "4" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_valtyp]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_cpcnt]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "0x7F" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_arg]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_decmul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_frcint" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_dac + 2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_cpcnt]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "0x80" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_cpcnt + 1]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Convert End angle to 0`255." );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "work_crcsum" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "ld_arg_single_real" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "single_407437" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "ld_dac_single_real" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "4" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_valtyp]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_crcsum]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "0x7F" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_arg]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_decmul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "bios_frcint" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_dac + 2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_crcsum]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "0x80" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_crcsum + 1]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Compare Start and End angle" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_cpcnt]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_savem]", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Get sin table" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "IX", "blib_get_sin_table" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "call_blib" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Initial value of Horizontal radius." );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_radiusx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cxoff1]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_radiusy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cyoff2]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cxoff2]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cyoff1]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	ƒÆ = 0[deg]¨45[deg]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_csclxy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_theta_loop" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		Move previous value to PREV section." );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "work_circle_cxoff1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "work_circle_prev_cxoff1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "8" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LDIR" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		X1 = cos(THETA) * Horizontal radius, Y2 = cos(THETA) * Vertical radius" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_cos" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_radiusx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cxoff1]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_radiusy]" );
	asm_line.set( "CALL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cyoff2]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		Y1 = sin(THETA) * Horizontal radius, X2 = sin(THETA) * Vertical radius" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_sin" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_radiusy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cyoff1]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_radiusx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cxoff2]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		Quadrant 0 (0[deg]...90[deg])" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant0_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_circle_quadrant0]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NZ", "_sub_circle_quadrant1_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "3" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_quadrant_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		Quadrant 1 (90[deg]...180[deg])" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant1_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_circle_quadrant1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NZ", "_sub_circle_quadrant2_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "128" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SUB", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_quadrant_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		Quadrant 2 (180[deg]...270[deg])" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant2_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_circle_quadrant2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NZ", "_sub_circle_quadrant3_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "A", "128" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "XOR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_quadrant_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "		Quadrant 3 (270[deg]`360[deg])" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant3_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_circle_quadrant3]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NZ", "_sub_circle_quadrant_end" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "NEG" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_quadrant_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_end" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "BIT", "", "5", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "NZ", "_sub_circle_line_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_csclxy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "", "_sub_circle_theta_loop" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Is angle B a drawing target?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Cy = 0: target, 1: not target" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_check_angle" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Which is larger, the start or end angle?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_savem]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "Z", "_sub_circle_check_angle_cond_or" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_check_angle_cond_and" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Is the target angle greater than the starting angle?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_cpcnt]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "Z", "_sub_circle_check_angle_left1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_check_angle_left1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " The target angle is greater than the start angle. Then, is the angle of target smaller than the end angle?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_crcsum]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "Z" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_check_angle_cond_or" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Is the target angle greater than the start angle?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_cpcnt]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "NC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " The target angle is smaller than the start angle. So is the target angle smaller than the end angle?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_crcsum]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " If bit0 of A is 0, X sign is inverted; if bit1 is 0, Y sign is inverted." );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Angle 0 to 31 (0[deg] to 45[deg]) on B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "C", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_check_angle" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_quadrant_line1_skip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Start point X1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centerx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_cxoff1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_quadrant_process_add_cx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_cx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_cx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_cx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_cx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gxpos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Start point Y1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centery]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_cyoff1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_quadrant_process_add_cy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_cy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_cy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_cy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_cy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gypos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " End point X1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centerx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_prev_cxoff1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_quadrant_process_add_pcx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_pcx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_pcx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_pcx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_pcx1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "C", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " End point Y1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centery]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_prev_cyoff1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_quadrant_process_add_pcy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_pcy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_pcy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_pcy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_pcy1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "EX", "", "DE", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_draw_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_line1_skip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "BC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "C", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "XOR", "", "A", "63" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_check_angle" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_quadrant_line2_skip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Start point X2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centerx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_cxoff2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_quadrant_process_add_cx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_cx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_cx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_cx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_cx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gxpos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Start point Y2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centery]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_cyoff2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_quadrant_process_add_cy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_cy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_cy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_cy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_cy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gypos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " End point X2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centerx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_prev_cxoff2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_quadrant_process_add_pcx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_pcx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_pcx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_pcx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_pcx2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "C", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " End point Y2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centery]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_prev_cyoff2]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_quadrant_process_add_pcy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_sub_pcy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SBC", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_quadrant_process_set_pcy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_add_pcy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_process_set_pcy2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "EX", "", "DE", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_draw_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_quadrant_line2_skip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_draw_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_gxpos]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_x_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gxpos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_x_reject_check" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_x_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "C", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "", "_sub_circle_draw_line_y" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_x_reject_check" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_x_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "C", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_draw_line_y" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_gxpos+1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "XOR", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "Z" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_draw_line_y" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_gypos]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_y_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gypos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "E" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "D" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "C", "_sub_circle_y_reject_check" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_y_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "E", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "D", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "", "bios_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_y_reject_check" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_y_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "E", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "D", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "NC", "bios_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_gypos+1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "XOR", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "NZ", "bios_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Clipping X-coordinates in HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " If clipping, return with Cy=1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_x_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_x_clip_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_x_clip_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_aspct1 + 1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "NC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_aspct1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Clipping Y-coordinates in HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " If clipping, return with Cy=1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_y_clip" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_y_clip_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_y_clip_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "Z", "_sub_circle_y_clip_skip2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "211" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_rg9sav]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "191" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_y_clip_skip2" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "192" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "NC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_rg9sav]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_y_clip_192" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CP", "", "A", "212" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "NC" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "211" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_y_clip_192" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "191" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SCF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_line_process" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Connect the center point and the end angle with a line segment?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_crcsum]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "NZ", "_sub_circle_draw_radius" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_end_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Connect the center point and the starting angle with a line segment?" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_cpcnt]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "Z" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Correction of problems with clockwise and counterclockwise shift depending on the position of the 8 quadrants" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "XOR", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "BIT", "", "5", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "Z", "_sub_circle_draw_radius" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_csclxy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_draw_radius" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Correct angle to resolution" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[work_csclxy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CPL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Correction of problems with clockwise and counterclockwise shift depending on the position of the 8 quadrants" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RRCA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "XOR", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "BIT", "", "5", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NZ", "_sub_circle_draw_radius_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_draw_radius_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_cos			; HL = cos(THETA)" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_radiusx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cxoff1]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_sin			; HL = sin(THETA)" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_radiusy]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CALL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_circle_cyoff1]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Start point X1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centerx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_cxoff1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gxpos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " Start pointY1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "[work_circle_centery]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_cyoff1]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "[work_gypos]", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " End point X1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "BC", "[work_circle_centerx]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", " I“_Y1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "DE", "[work_circle_centery]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "", "_sub_circle_draw_line" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	HL = HL * BC >> 8, HL is signed, BC is unsigned." );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	   = (HL * C >> 8) + HL * B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_mul" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "OR", "", "A", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "PUSH", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JP", "P", "_sub_circle_skip_abs" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CPL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CPL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "INC", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_skip_abs" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "EX", "", "DE", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "8" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_mul_1st8bit" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SLA", "", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RL", "", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SLA", "", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_mul_1st8bit_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_mul_1st8bit_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NZ", "_sub_circle_mul_1st8bit" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RL", "", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_mul_2nd8bit" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "INC", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_mul_2nd8bit" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SRL", "", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "NC", "_sub_circle_mul_2nd8bit_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "HL", "DE" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_mul_2nd8bit_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SLA", "", "E" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RL", "", "D" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "INC", "", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DJNZ", "", "_sub_circle_mul_2nd8bit" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "POP", "", "AF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "P" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CPL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "L" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CPL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "INC", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	Get cos(THETA): A = THETA (0:0[deg]`256:360[deg]) ¨ A = cos(THETA)" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_cos" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "SUB", "", "A", "64" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "COMMENT", "", "	sinƒÆ‚ğ•Ô‚·: A = THETA (0:0[deg]`256:360[deg]) ¨ A = sin(THETA)" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_sin" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "B", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "0x3F" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "Z", "_sub_circle_sin_special" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "BIT", "", "6", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "JR", "Z", "_sub_circle_sin_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "NEG" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_sin_skip1" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "AND", "", "A", "0x3F" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "ADD", "", "A", "work_buf & 0x0FF" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "work_buf >> 8" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "A", "[HL]" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "H", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RL", "", "B" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "CPL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "L", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "INC", "", "HL" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LABEL", "", "_sub_circle_sin_special" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "LD", "", "HL", "0" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "BIT", "", "6", "A" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "Z" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "INC", "", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RLA" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET", "C" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "DEC", "", "H" );
	this->subroutines.push_back( asm_line );
	asm_line.set( "RET" );
	this->subroutines.push_back( asm_line );
