        DEFB        0FEh
        DEFW        start_address
        DEFW        end_address
        DEFW        start_address
        ORG         08010h
start_address:
        LD          (save_stack), SP
program_start:
work_csry                       equ 0F3DCh
bios_chgmod                     equ 0005Fh
        LD          HL, (work_csry)
        LD          H, 0
        LD          A, L
        CALL        bios_chgmod
program_termination:
        LD          SP, (save_stack)
        RET
save_stack:
        DEFW        0
end_address:
