; ------------------------------------------------------------------------
; Compiled by MSX-BACON from test.asc
; ------------------------------------------------------------------------
; 
bios_chgmod                     equ 0005Fh
; BSAVE header -----------------------------------------------------------
        DEFB        0FEh
        DEFW        start_address
        DEFW        end_address
        DEFW        start_address
        ORG         08010h
start_address:
        LD          (save_stack), SP
        LD          DE, program_start
        JP          program_run
program_start:
        LD          HL, 1
        LD          A, L
        CALL        bios_chgmod
        LD          HL, str_0
        PUSH        HL
        CALL        puts
        POP         HL
        CALL        free_string
        LD          HL, str_1
        CALL        puts
        LD          HL, str_2
        PUSH        HL
        CALL        puts
        POP         HL
        CALL        free_string
        LD          HL, str_3
        CALL        puts
        JP          program_termination
program_termination:
        LD          SP, (save_stack)
        RET
program_run:
        LD          HL, heap_start
        LD          (heap_next), HL
        LD          HL, (save_stack)
        LD          SP, HL
        PUSH        DE
        LD          DE, 256
        XOR         A
        SBC         HL, DE
        LD          (heap_end), HL
        RET
puts:
        LD          B, (HL)
_puts_loop:
        INC         HL
        LD          A, (HL)
        RST         018h
        DJNZ        _puts_loop
        RET
free_string:
        PUSH        HL
        LD          E, (HL)
        LD          D, 0
        ADD         HL, DE
        INC         HL
        INC         DE
        SBC         HL, DE
        POP         HL
        RET
        LD          (heap_next), HL
        RET
str_0:
        DEFB        00Dh, 048h, 045h, 04Ch, 04Ch, 04Fh, 02Ch, 020h, 057h, 04Fh, 052h, 04Ch, 044h, 021h
str_1:
        DEFB        002h, 00Dh, 00Ah
str_2:
        DEFB        013h, 054h, 068h, 069h, 073h, 020h, 069h, 073h, 020h, 04Dh, 053h, 058h, 02Dh, 042h, 041h, 043h, 04Fh, 04Eh, 021h, 021h
str_3:
        DEFB        002h, 00Dh, 00Ah
save_stack:
        DEFW        0
heap_next:
        DEFW        0
heap_end:
        DEFW        0
heap_start:
end_address:
